apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJSWFpJYmpwbmFIQmZaV05vUWxWUFZGZEVNbko2VEVGeWExQldiamg2YVZCelZIbGpiekJqTkU5NFIxUmgiDQogICAgfQ0KICB9DQp9
type: kubernetes.io/dockerconfigjson
